Ninja Cart/ninja_kart/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^store/', include('store.urls', namespace = 'store')),
    url(r'^admin/', include(admin.site.urls)),
)

Ninja Cart/store/urls.py
from django.conf.urls import patterns, url

from store import views

urlpatterns = patterns('',
    url(r'^$', views.index, name='index'),
    # ex: /item/5/
    url(r'^(?P<item_id>\d+)/$', views.detail, name='detail'),
    # ex: /polls/5/results/
    url(r'^(?P<item_id>\d+)/add/$', views.add, name='add'),
    # ex: /polls/5/vote/
    url(r'^cart/$', views.cart, name='cart'),
    url(r'^(?P<item_id>\d+)/remove/$', views.remove, name='remove'),
)

Ninja Cart/store/models.py
from django.db import models
from django.utils.html import format_html

# Create your models here.

class Item(models.Model):
	description = models.CharField(max_length = 200)
	image = models.CharField(max_length = 200)
	title = models.CharField(max_length = 100)
	price = models.IntegerField(max_length = 11)

	def item_html(self):
		return format_html('<li class="col-3 col-sm-3 col-md-3" style="height: 450px;">' 
												'<div style="height: 256px;" >'
            						'<div  style="width:190px;height:190px;display: block;border: 2px solid rgb(236, 231, 220); position: relative;overflow: hidden;">'
              					'<img src="{0}" alt="" width="200px" height="301px"  style="height: 370px;margin: -120px 0px -5px 0px;" />'
												'</div><div class="caption">'
                				'<h6 style="height:22px;">{1}</h6>'
                				'<p class="text-muted">${2}.00 </p> '
					 							'</div>'
          							'</div>'
												'<a href="#" class="btn btn-primary btn-block">'
												'Get Item &raquo;'
												'</a></li>',
												str(self.image), str(self.title), str(self.price))

	def __unicode__(self):
		return u'%s %d' % (self.title, self.price)

class Size(models.Model):
	size = models.CharField(max_length = 15)

	def __unicode__(self):
		return u" %s " % self.size

class Item_Qty(models.Model):
	profile = models.ForeignKey(Item)
	size = models.ForeignKey(Size)
	quantity = models.IntegerField(max_length = 10)
	pending = models.IntegerField(max_length = 10)

	def __unicode__(self):
		return u'%d %d %d' %  (self.profile_id, self.size_id, self.quantity)

class User(models.Model):
	f_name = models.CharField(max_length = 30)
	l_name = models.CharField(max_length = 50)
	email = models.CharField(max_length = 30)
	address = models.CharField(max_length = 100)

	def __unicode__(self):
		return u'%s %s %s %s' %  (self.f_name, self.l_name, self.email, self.address)

class Cart(models.Model):
	item = models.IntegerField(max_length = 10)
	qty = models.IntegerField(max_length = 10)
	session = models.IntegerField(max_length = 10)

	def __unicode__(self):
		return u'%d %d' %  (self.item_id)

Ninja Cart/store/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.template import RequestContext, loader
from django.core.urlresolvers import reverse
from store.models import Item, Item_Qty, Size, User, Cart
from django.contrib import messages

DANGER = 50

def index(request):
		item_list = Item.objects.all()
		context = { 'items' : item_list }
		return render(request, 'store/item.html', context)

def detail(request, item_id):
	try:
			profile = Item.objects.get(pk = item_id)
	except Item_Profile.DoesNotExist:
		raise Http404
	options = Size.objects.all()
	for o in options:
		item = Item_Qty.objects.filter(profile_id = item_id, size = o.id)
		if not item:
			o.stat = 'disabled="disabled"'
		else:
			o.stat = ''
	return render(request, 'store/item.html', {'profile' : profile, 'options' : options})

def add(request, item_id):
		i = get_object_or_404(Item, pk = item_id)
		try:
			item = Item_Qty.objects.get(profile_id = item_id, size = request.POST['size'])
			item.quantity -= 1
			item.pending += 1
			try:
				check = Cart.objects.get(item = item.id)
				check.qty +=1
				check.save()
			except Cart.DoesNotExist:
				c = Cart(item = item.id, qty = 1)
				c.save()
			item.save()
			messages.success(request, 'Item was added to your cart.')
		except (KeyError, Item.DoesNotExist):
			messages.warning(request, 'That item does not exist.')
		return HttpResponseRedirect(reverse('store:index'))

def cart(request):
	total = 0
	subtotal = 0
	items = Cart.objects.all()
	for i in items:
		num = []
		count = 1
		info = Item_Qty.objects.get(id = i.item)
		number = info.quantity
		size = Size.objects.get(id = info.size_id)
		i.size = size.size
		more = Item.objects.get(id = info.profile_id)
		i.title = more.title
		i.price = more.price
		i.total = int(more.price) * int(i.qty)
		subtotal += i.total
	total = subtotal + 10
	return render(request, 'store/cart.html', {'items' : items, 'total' : total, 'subtotal' : subtotal})


def remove(request, item_id):
	qty = 0
	item = Cart.objects.get(item = item_id)
	qty = item.qty
	profile = Item_Qty.objects.get(id = item_id)
	profile.quantity += qty
	profile.pending -= qty
	profile.save()
	item.delete()
	messages.warning(request, 'Item(s) have been removed from your cart')
	return HttpResponseRedirect(reverse('store:cart'))

Ninja Cart/store/templates/store/base.html
<!DOCTYPE html5>
<html>
  <head>
    <link href="/static/store/css/bootstrap.css" rel="stylesheet">
    <link href="/static/store/css/thumbnail-gallery.css" rel="stylesheet">
    <link href='/static/store/css/bootstrap-responsive.min.css' rel="stylesheet">
    <link src="/static/store/select/bootstrap-select/bootstrap-select.css" rel="stylesheet">
    <script src="/static/store/select/bootstrap-select/bootstrap-select.js"></script>
    <script src="/static/store/js/bootstrap.js"></script>
    <script src="http://code.jquery.com/jquery-1.9.1.js"></script>
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
    <script src="http://netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"></script>
    <script src="http://code.jquery.com/ui/1.10.3/jquery-ui.js"></script>
    <title>Ninja Kart</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
  </head>
  <body>
    <div class="container">
      <div class="navbar navbar-default" role="navigation">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">Ninja Kart</a>
        </div>
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li><a href="{% url 'store:index' %}">Home</a></li>
            <li><a href="{% url 'store:index' %}">Store</a></li>
            <li><a href="{% url 'store:cart' %}">Cart</a></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </div>
    {% block header %} 
    {% endblock %}
    <div class="container">
      <div class="jumbotron" style="border-radius: 3px;text-align: center;background-color: transparent;padding: 10px;padding-top: 48px;">
      </div>
    </div>
    {% if messages %}
    <div class="container"> 
    <div class="col-md-offset-1 col-9 col-sm-9 col-md-9">
      <div class="messages ">
      {% for message in messages %}
        <div class="alert alert-{{ message.tags }} alert-dismissable">
          <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
          {{ message }}
        </div>
        {% endfor %}
      </div>
    </div></div>
    {% endif %}
    {% block content %} 
    {% endblock %}
  </body>
</html>

Ninja Cart/store/templates/store/base_store.html
{% extends "/store/base.html" %}
{% block content %}
<div class="container">
  <div class="row">
    	{% if items %}
      <legend>Apparel</legend>
      <ul class="thumbnails list-unstyled">
    	{% for item in items %}
         <li class="col-3 col-sm-3 col-md-3" style="height: 450px;">
         <div class="col-sm-offset-1">
         <div style="height: 256px;" >
            <div  style="width:190px;height:190px;display: block;border: 2px solid rgb(236, 231, 220); position: relative;overflow: hidden;">
               <!-- <img src="{{item.image}}" alt="" class="img-responsive"  style="height: 370px;margin: -120px 0px -5px 0px;" /> -->
               <img src="{{item.image}}" alt="" width="200px" height="301px"  style="height: 370px;margin: -120px 0px -5px 0px;" />
               <!-- clip: shape(top, right, botton, left);-->
            </div>
            <div class="caption">
                <h6 style="height:22px;">{{item.title}}</h6>
                <p class="text-muted">${{item.price}}.00 </p> 
					 </div>
          </div>
          <a href="/store/{{item.id}}/" class="btn btn-primary btn-block">
							Get Item &raquo;
					</a>
          </div>
        </li>
    	{% endfor %}
      </ul>
    	{% else %}
      <div class="col-12 col-sm-12 col-md-12">
          <div class="row">
            <div class="col-5 col-sm-5 col-md-5">
              <img src="{{profile.image}}" class="img-thumbnail">
            </div>
            <div class="col-7 col-sm-7 col-md-7">
            <form method="POST" action="/add/{{pro.id}}" class="form-horizontal" role="form">
              <h3> {{profile.title}} </h3> 
              <h4> ${{profile.price}}.00 </h4>
              <br>
              <div class="form-group">
                <label class="col-sm-2 control-label" ><h4>Overview: </h4> </label>
                <div class="col-sm-5">
                <h4> {{profile.description}} </h4>
                </div>
              </div>
              <div class="form-group">
                <label for="size" class="col-sm-2 control-label" ><h4>Size:</h4></label>
                <div class="col-sm-5">
                <select id="size" class="btn btn-default" name="size">
                  {% for option in options %}
                    <option value="{{option}}"> {{option}} </option>
                  {% endfor %} 
                </select>
              </div>
              </div>
              <div class="form-group"> 
                <div class="col-sm-offset-2 col-sm-5">
                  <button type="submit" class="btn btn-primary">Add to Cart &raquo;</button>
                </div>
              </div>
              </form>
            </div>
          </div>
      </div>
    	{% endif %}
  </div>
</div>
{% endblock %}

Ninja Cart/store/templates/store/cart.html
{% extends 'store/base.html' %}
{% block content %}


<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-10 col-md-offset-1">
      <table class="table table-hover">
        <thead>
          <tr>
            <th>Product</th>
            <th>Quantity</th>
            <th class="text-center">Price</th>
            <th class="text-center">Total</th>
            <th> </th>
            </tr>
        </thead>
        <tbody>
        {% for item in items%}
          <tr>
            <td class="col-sm-8 col-md-6">
              <div class="media">
                <a class="thumbnail pull-left" href="#"> <img class="media-object" src="http://icons.iconarchive.com/icons/custom-icon-design/flatastic-2/72/product-icon.png" style="width: 72px; height: 72px;"> </a>
                  <div class="media-body">
                    <h4 class="media-heading"><a href="#">{{item.title}}</a></h4>
                    <h5 class="media-heading"><a href="#">{{item.size}}</a></h5>
                  </div>
              </div>
            </td>
            <td class="col-sm-1 col-md-1" style="text-align: center">
							<div class="btn-group">
  								<button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown"> {{item.qty}} <span class="caret"></span>
  								</button>
  									<ul class="dropdown-menu" role="menu">
                        <li><a href="#">9</a></li>
                    </ul>
									</div>
            </td>
            <td class="col-sm-1 text-center"><strong>${{item.price}}.00</strong></td>
            <td class="col-sm-1 col-md-1 text-center"><strong>${{item.total}}.00</strong></td>
            <td class="col-sm-1 col-md-1">
              <a href="{% url 'store:remove' item.item %}" class="btn btn-danger"> Remove All &raquo;</a> 
            </td>
          </tr>
        {% endfor %}
          <tr>
            <td>   </td>
            <td>   </td>
            <td>   </td>
            <td><h5>Subtotal</h5></td>
            <td class="text-right"><h5><strong>${{subtotal}}.00</strong></h5></td>
          </tr>
          <tr>
            <td>   </td>
            <td>   </td>
            <td>   </td>
            <td><h5>Shipping</h5></td>
            <td class="text-right"><h5><strong>$10.00</strong></h5></td>
          </tr>
          <tr>
              <td>   </td>
              <td>   </td>
              <td>   </td>
              <td><h3>Total</h3></td>
              <td class="text-right"><h3><strong>${{total}}.00</strong></h3></td>
          </tr>
          <tr>
            <td>   </td>
            <td>   </td>
            <td>   </td>
            <td>
              <a href="{% url 'store:index' %}" class="btn btn-default">
                <span class="glyphicon glyphicon-shopping-cart"></span> Continue Shopping
              </a>
            </td>
            <td>
              <button type="button" class="btn btn-success">
                Checkout <span class="glyphicon glyphicon-play"></span>
              </button>
            </td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</div>
{% endblock %}

Ninja Cart/store/templates/store/home.html
{% extends 'base.html' %}
{% block header %}

<div class="jumbotron">
      <div class="container">
        <h1>Hello, world!</h1>
        <p>This is a template for a simple marketing or informational website. It includes a large callout called a jumbotron and three supporting pieces of content. Use it as a starting point to create something more unique.</p>
        <p><a class="btn btn-primary btn-lg" role="button">Learn more &raquo;</a></p>
      </div>
</div>

{% endblock %}

Ninja Cart/store/templates/store/index.html
<html>
	<head>
		<title>Ninja Kart Checkout </title>
	</head>
	<body>
		<h1> Hello {{user.fname}}!</h1>
	</body>
</html>

Ninja Cart/store/templates/store/item.html
{% extends "store/base.html" %}
{% block content %}

<div class="container">
  <div class="row">
    {% if items %}
    <div class="col-sm-offset-1 col-sm-9 col-md-9">
      <legend>Apparel</legend>
    </div>
    <div class="col-sm-offset-1 col-sm-11 col-md-11">
      <ul class="thumbnails list-unstyled">
    	{% for item in items %}
        <li class="col-3 col-sm-3 col-md-3" style="height: 450px;">
         <div style="height: 256px;" >
            <div  style="width:200px;height:200px;display: block;border: 2px solid rgb(236, 231, 220); position: relative;overflow: hidden;">
               <img src="{{item.image}}" alt="" width="200px" height="301px"  style="height: 370px;margin: -120px 0px -5px 0px;" />
            </div>
            <div class="caption" >
                <h6 style="height:22px;">{{item.title}}</h6>
                <p class="text-muted">${{item.price}}.00 </p> 
					  </div>
            <div style="width:200px;height:200px;">
              <a href="{% url 'store:detail' item.id %}" class="btn btn-primary btn-block">
                Get Item &raquo;
              </a>
            </div>
         </div>
        </li>
    	 {% endfor %}
       </ul>
      </div>
    	{% else %}<div class="container">
        <div class="col-sm-offset-2 col-9 col-sm-9 col-md-9">
          <div class="row">
            <div class="col-5 col-sm-5 col-md-5">
              <img src="{{profile.image}}" class="img-thumbnail">
            </div>
            <div class="col-7 col-sm-7 col-md-7">
            <form method="POST" action="{% url 'store:add' profile.id %}" class="form-horizontal" role="form">
            {% csrf_token %}
              <h3> {{profile.title}} </h3> 
              <h4> ${{profile.price}}.00 </h4>
              <br>
              <div class="form-group">
                <label class="col-sm-2 control-label" ><h4>Overview: </h4> </label>
                <div class="col-sm-5">
                  <h4> {{profile.description}} </h4>
                </div>
              </div>
              <div class="form-group">
                <label for="size" class="col-sm-2 control-label" ><h4>Size:</h4></label>
                <div class="col-sm-5">
                <select id="size" class="selectpicker form-control"  name="size">
                  {% for option in options %}
                    <option value="{{option.id}}" {{option.stat}}> {{option}} </option>
                  {% endfor %} 
                </select>
              </div>
              </div>
              <div class="form-group"> 
                <div class="col-sm-offset-2 col-sm-5">
                  <button type="submit" class="btn btn-primary">Add to Cart &raquo;</button>
                </div>
              </div>
              </form>
            </div>
          </div>
        </div></div>
    	{% endif %}
  </div>
</div>
{% endblock %}

Ninja Cart/store/templates/store/show_all.html
{% extends "base.html" %}
{% block content %}
<div class="container">
		<div class="row">
    {% for item in items %}
         <div class="col-4 col-sm-4 col-md-4" style="height: 400px;">
          <div style="height: 310px;">
              <img src="{{item.image}}" alt="" class="img-rounded img-responsive" style="width: 95%;" />
          </div>
              <div class="caption">
              	<h5><a href='#' type="button">{{item.title}}</a></h5>
              	<p class="text-muted">${{item.price}}.00 </p>
								</div>
          </div>
        {% endfor %}
      </div>
		</div>
</div>
<script type="text/javascript">
    $(function(){
        $(".dropdown-toggle").dropdown();
    });
</script>
{% endblock %}

Ninja Cart/store/templates/store/test copy.html
class Cart_Itm(object):
	count = 0
  	
  	def __init__(self, title, price, size):
  		self.title = title
  		self.price = price
  		self.size = size 
  		Cart_Itm.count += 1

  	def display_qty(self):
  		return Cart_Itm.count

  	def __repr__(self):
  		return "%s%s%s%s" % (self.title, self.price, self.size, Cart_Itm.count)

def check_model():
	count = 0
	rup = []
	items = Cart.query.all()
	for i in items:
		profile = Profile.query.get(i.profile_num)
		rup = Cart_Itm(title = profile.title, price = profile.price, size = i.size)
		rup

Ninja Cart/store/templates/store/trash.html
<link href="/static/css/bootstrap-select/bootstrap-select.min.css" rel="stylesheet">
<link href="/static/css/bootstrap-select/bootstrap-select.css" rel="stylesheet">
<link href="/static/css/jumbotron-narrow.css" rel="stylesheet">


<!DOCTYPE html5>
<html>
  <head>
    <link href="/static/css/bootstrap.css" rel="stylesheet">
    <link href="/static/css/jumbotron.css" rel="stylesheet">
    <script src="/static/css/bootstrap-select/bootstrap-select.js"></script>
    <script src="/static/css/bootstrap-select/bootstrap-select.min.js"></script>
    <script src="/static/js/bootstrap.js"></script>
    <script src="http://code.jquery.com/jquery-1.9.1.js"></script>
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
    <script src="http://netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"></script>
    <script src="http://code.jquery.com/ui/1.10.3/jquery-ui.js"></script>
    <title>Ninja Kart</title>
  </head>
  <body>
 <div class="container"> 
    <div class="navbar navbar-fixed-top navbar-inverse" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">Project name</a>
        </div>
        <div class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li><a href="#">Home</a></li>
            <li><a href="{{url_for('store')}}">Store</a></li>
            <li><a href="{{url_for('view_cart')}}">Cart</a></li>
          </ul>
        </div><!-- /.nav-collapse -->
      </div><!-- /.container -->
    </div><!-- /.navbar -->
</div>
<div class="container">
    {% with messages = get_flashed_messages() %}
    {% if messages %}
      <div>
      {% for message in messages %}
        <p class="text-success">{{ message }}</p>
      {% endfor %}
      </div>
    {% endif %}
    {% endwith %}
</div>
    {% block content %} 
    {% endblock %}
  </body>
</html>